In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('white')
%matplotlib inline

import math

In [3]:
reviewsDF = pd.read_csv('boosted_beer_reviews.csv')

In [4]:
reviewsDF.head()

Unnamed: 0  brewery_id                brewery_name  review_time  \
0          10         163      Amstel Brouwerij B. V.   1010963392   
1       53684          81     Heineken Nederland B.V.   1013799042   
2       91325         140   Sierra Nevada Brewing Co.   1010961818   
3       96343         140   Sierra Nevada Brewing Co.   1013106080   
4      123281         273  SweetWater Brewing Company   1077762315   

   review_overall  review_aroma  review_appearance review_profilename  \
0               3           2.0                3.0            fodeeoz   
1               3           2.0                3.0            fodeeoz   
2               4           5.0                4.5            fodeeoz   
3               3           3.5                3.0            fodeeoz   
4               4           3.0                3.5            fodeeoz   

                beer_style  review_palate  review_taste  \
0              Light Lager            2.5           2.5   
1          Euro Pale Lager            2.5           2.5   
2  American Pale Ale (APA)            4.5           5.0   
3  American Pale Wheat Ale            3.5           3.5   
4  American Pale Ale (APA)            4.5           4.5   

                       beer_name  beer_abv  beer_beerid  Boosted  
0                   Amstel Light       3.5          436        3  
1            Heineken Lager Beer       5.0          246        6  
2         Sierra Nevada Pale Ale       5.6          276       10  
3       Sierra Nevada Wheat Beer       4.4          282       13  
4  Sweetwater 420 Extra Pale Ale       5.4          751       17

In [5]:
from sklearn.model_selection import train_test_split

from mord import LogisticAT, LogisticIT, LAD, OrdinalRidge

ModuleNotFoundError: No module named 'mord'

In [ ]:
filteredReviewsDF = 

In [15]:
X_train, X_test, y_train, y_test = train_test_split(filteredReviewsDF.drop('review_overall',axis=1), 
                                                    filteredReviewsDF['review_overall'], test_size=0.30, 
                                                    random_state=101)


In [16]:
model_AT = LogisticAT(alpha=0)
pred_AT = model_AT.fit(X_train, y_train)
results_AT = pred_AT.predict(X_test)

In [17]:
model_IT = LogisticIT(alpha=0)
pred_IT = model_IT.fit(X_train, y_train)
results_IT = pred_IT.predict(X_test)

In [18]:
model_LAD = LAD()
pred_LAD = model_LAD.fit(X_train, y_train)
results_LAD = pred_LAD.predict(X_test)

/Users/paulojosecb/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


In [19]:
model_Ordinal_Ridge = OrdinalRidge(alpha=0)
pred_Ordinal = model_Ordinal_Ridge.fit(X_train, y_train)
results_Ordinal = pred_Ordinal.predict(X_test)

In [20]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [21]:
print('LogisticAT: ', accuracy_score(y_test, results_AT))

LogisticAT:  0.6513121051649097


In [22]:
print('LogisticIT: ', accuracy_score(y_test, results_IT))

LogisticIT:  0.6512040321075229


In [23]:
print('LAD: ', accuracy_score(y_test, results_LAD))


LAD:  0.6489909906369433


In [24]:
print('OrdinalRidge: ', accuracy_score(y_test, results_Ordinal))

OrdinalRidge:  0.647143923837969


In [25]:
from sklearn.metrics import confusion_matrix


In [26]:
print('LogisticAT: ', confusion_matrix(y_test, results_AT))

LogisticAT:  [[   915   2449   1587    468      0]
 [   287   5187  13107   4717      0]
 [    96   2843  49119  66594      0]
 [    24    858  26255 209942      3]
 [    17    100   1028  21529      7]]


In [27]:
print('LogisticIT: ', confusion_matrix(y_test, results_IT))

LogisticIT:  [[  1708   1707   1486    518      0]
 [   985   4655  12473   5185      0]
 [   343   2716  44332  71261      0]
 [    92    819  21741 214430      0]
 [    34     85    925  21636      1]]


In [28]:
print('LAD: ', confusion_matrix(y_test, results_LAD))


LAD:  [[    16   2690   2270    441      2]
 [     0   3266  15662   4355     15]
 [     0   1388  56853  60313     98]
 [     0    417  33133 202369   1163]
 [     0     75   1242  19643   1721]]


In [29]:
print('OrdinalRidge: ', confusion_matrix(y_test, results_Ordinal))

OrdinalRidge:  [[   180   2823   2061    353      2]
 [    25   3987  15723   3554      9]
 [     5   1805  64275  52509     58]
 [     2    530  41953 193875    722]
 [     3     83   1509  19930   1156]]
